SMUniversity/Models/BalanceTransactionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SMUniversity.Models
{
    public class BalanceTransactionViewModel
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public string TitleAr { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int TransactionTypeID { get; set; }
        public string PaymentMethod { get; set; }
    }
}

SMUniversity/Controllers/BalanceTransactionController.cs
using SMUModels;
using SMUModels.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;

namespace SMUniversity.Controllers
{
    public class BalanceTransactionController : Controller
    {
        admin_SMUniversityEntities _Context = new admin_SMUniversityEntities();

        // GET: BalanceTransaction
        //public ActionResult Index()
        //{
        //    return View();
        //}

        public ActionResult PendedChargeRequest()
        {
            if (Session["UserID"] == null || Session["BranchID"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }

        public JsonResult ConfirmTransaction(int TransactionID)
        {
            try
            {
                TblBalanceTransaction _BalanceTrans = _Context.TblBalanceTransactions.Where(a => a.ID == TransactionID).SingleOrDefault();
                if (_BalanceTrans != null)
                {
                    TblInvoice _Invoice = _Context.TblInvoices.Where(a => a.BalanceTransactionID == _BalanceTrans.ID).FirstOrDefault();

                    _BalanceTrans.Pending = false;
                    _BalanceTrans.UserID = 1;
                    _BalanceTrans.CreatedDate = DateTime.Now;
                    _BalanceTrans.UpdatedDate = DateTime.Now;
                    _BalanceTrans.TblStudent.Balance += decimal.Parse(_BalanceTrans.Price.ToString());

                    _Invoice.Pending = true;

                    _Context.SaveChanges();

                    string TitleAr1 = "سمارت مايند الجامعه";
                    string TitleEn1 = "SmartMind University";
                    string DescriptionAr1 = "تم تأكيد عمليه الشحن بمبلغ  " + _BalanceTrans.Price + " رصيدك الحالي : " + _BalanceTrans.TblStudent.Balance + "د.ك";
                    string DescriptionEn1 = "Your recharge of " + _BalanceTrans.Price + " D.K has been confirmed succefully, Your current balace is : " + _BalanceTrans.TblStudent.Balance + " D.K";

                    Push(int.Parse(_BalanceTrans.StudentID.ToString()), 0, TitleAr1, TitleEn1, DescriptionAr1, DescriptionEn1, 0);

                    TempData["notice"] = "تم تأكيد شحن مبلغ " + _BalanceTrans.Price + " ودخوله في حساب الطالب " + _BalanceTrans.TblStudent.FirstName + " " + _BalanceTrans.TblStudent.SecondName + " " + _BalanceTrans.TblStudent.ThirdName + " بنجاح";
                    //return RedirectToAction("PendedChargeRequest");
                    return Json("OK");
                }
                else
                {
                    TempData["notice"] = "ERROR while processing!";
                    return Json("ERROR");
                }
            }
            catch (Exception ex)
            {
                TempData["notice"] = "ERROR while processing!";
                return Json("ERROR");
            }
        }

        //[HttpPost]
        public ActionResult index(jQueryDataTableParamModel param)
        {
            if (Session["UserID"] == null || Session["BranchID"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                //int BranchID = int.Parse(Session["BranchID"].ToString());

                List<TblBalanceTransaction> oData = new List<TblBalanceTransaction>();
                IEnumerable<TblBalanceTransaction> filteredData;
                //Check whether the companies should be filtered by keyword
                if (!string.IsNullOrEmpty(param.sSearch))
                {
                    string sSearch = param.sSearch.Trim().ToLower();

                    filteredData = _Context.TblBalanceTransactions.Where(c => c.IsDeleted != true && c.Pending == true).ToList();

                    foreach (var item in filteredData)
                    {
                        if (item.StudentID.ToString().ToLower().Contains(sSearch) || (item.TblStudent.FirstName + " " + item.TblStudent.FirstName + " " + item.TblStudent.FirstName).ToLower().Contains(sSearch))
                        {
                            oData.Add(item);
                        }
                    }

                    filteredData = oData;
                }
                else
                {
                    filteredData = _Context.TblBalanceTransactions.Where(c => c.IsDeleted != true && c.Pending == true).ToList();

                }

                var sortColumnIndex = Convert.ToInt32(Request["iSortCol_0"]);
                Func<TblBalanceTransaction, string> orderingFunction = (c => sortColumnIndex == 0 ? Convert.ToString(c.StudentID) :
                                                               sortColumnIndex == 1 ? string.Join(c.TblStudent.FirstName, c.TblStudent.SecondName, c.TblStudent.ThirdName) :
                                                               sortColumnIndex == 2 ? c.TblStudent.PhoneNumber :
                                                               "");

                var sortDirection = Request["sSortDir_0"]; // asc or desc
                if (sortDirection == "asc")
                    filteredData = filteredData.OrderBy(orderingFunction);
                else
                    filteredData = filteredData.OrderByDescending(orderingFunction);

                if (param.iDisplayLength == -1)
                {
                    param.iDisplayLength = filteredData.Count();
                }

                var displayedData = filteredData.Skip(param.iDisplayStart).Take(param.iDisplayLength).ToList();

                var result = from c in displayedData select new[] { Convert.ToString(c.StudentID), c.TblStudent.FirstName + " " + c.TblStudent.SecondName + " " + c.TblStudent.ThirdName, c.TblStudent.PhoneNumber };
                var jsonResult = Json(new
                {
                    sEcho = param.sEcho,
                    iTotalRecords = _Context.TblBalanceTransactions.Count(),
                    iTotalDisplayRecords = filteredData.Count(),
                    aaData = result,

                },
                            JsonRequestBehavior.AllowGet);

                jsonResult.MaxJsonLength = int.MaxValue;

                return jsonResult;
                //return Json(new
                //{
                //    sEcho = param.sEcho,
                //    iTotalRecords = _Context.Tbl_Students.Count(),
                //    iTotalDisplayRecords = filteredData.Count(),
                //    aaData = result,

                //},
                //            JsonRequestBehavior.AllowGet);
            }
        }

        private void Push(int StudentID, int LecturerID, string TitleAr, string TitleEn, string DescriptionAr, string DescriptionEn, int NotTypeID)
        {
            try
            {
                bool res = PushNotification.Push(StudentID, LecturerID, TitleAr, TitleEn, DescriptionAr, DescriptionEn, NotTypeID);
                var regNotification = new TblNotification { StudentID = StudentID, TitleAr = TitleAr, TitleEn = TitleEn, DescriptionAr = DescriptionAr, DescriptionEn = DescriptionEn, CreatedDate = DateTime.Now };

                _Context.TblNotifications.Add(regNotification);
                _Context.SaveChanges();
            }
            catch (Exception ex)
            {
            }

        }

    }
}

SMUniversity/Views/BalanceTransaction/ConfirmTransaction.cshtml
@*<link rel="stylesheet" href="https://unpkg.com/bootstrap/dist/css/bootstrap.min.css" />*@
<link rel="stylesheet" href="https://unpkg.com/animate.css/animate.css" type="text/css" />
<link rel="stylesheet" href="https://unpkg.com/rmodal/dist/rmodal.css" type="text/css" />
<script type="text/javascript" src="https://unpkg.com/rmodal/dist/rmodal.js"></script>
<style type="text/css">

    .modal .modal-dialog {
        width: 400px;
    }
</style>
<script type="text/javascript">
    window.onload = function () {
        var modal = new RModal(document.getElementById('modal'), {
            //content: 'Abracadabra'
            beforeOpen: function (next) {
                console.log('beforeOpen');
                next();
            }
            , afterOpen: function () {
                console.log('opened');
            }

            , beforeClose: function (next) {
                console.log('beforeClose');
                next();
            }
            , afterClose: function () {
                console.log('closed');
            }
            // , bodyClass: 'modal-open'
            // , dialogClass: 'modal-dialog'
            // , dialogOpenClass: 'animated fadeIn'
            // , dialogCloseClass: 'animated fadeOut'

            // , focus: true
            // , focusElements: ['input.form-control', 'textarea', 'button.btn-primary']

            // , escapeClose: true
        });

        document.addEventListener('keydown', function (ev) {
            modal.keydown(ev);
        }, false);

        document.getElementById('showModal').addEventListener("click", function (ev) {
            ev.preventDefault();
            modal.open();
        }, false);

        window.modal = modal;
    }
</script>

SMUniversity/Views/BalanceTransaction/PendedChargeRequest.cshtml
@{
    ViewBag.Title = "PendedChargeRequest";
    Layout = "~/Views/Shared/_Layout.cshtml";
    SMUModels.admin_SMUniversityEntities _Context = new SMUModels.admin_SMUniversityEntities();
}

<link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="~/Content/DataTables/css/buttons.dataTables.min.css" rel="stylesheet" />

<script src="~/Scripts/DataTables/jquery.dataTables.js"></script>
<script src="https://editor.datatables.net/extensions/Editor/js/dataTables.editor.min.js"></script>
@*<script src="~/Scripts/DataTables/dataTables.buttons.min.js"></script>*@
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
<script src="~/Scripts/DataTables/but@*t*@ons.html5.min.js"></script>

<script src="~/Scripts/BalanceTransaction/PendedChargeRequest.js"></script>

<input type="hidden" id="TransactionID" />

<div id="main-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!--Top header start-->
                <h3 class="ls-top-header"></h3>
                <!--Top header end -->
                <!--Top breadcrumb start -->
                <ol class="breadcrumb">
                    <li><a href="/Home/Index"><i class="fa fa-home"></i></a></li>
                    <li class="active"><a href="/BalanceTransaction/PendedChargeRequest">الرئيسية</a></li>
                    @*<li class="active"><a href="/BalanceTransaction/PendedChargeRequest">اضافة تخصص</a></li>*@
                </ol>
                <!--Top breadcrumb start -->
            </div>
        </div>
        <!-- Main Content Element  Start-->

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"></h3>
                    </div>
                    <table id="myDataTable" class="table table-striped table-bordered table-hover display">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>الطالب</th>
                                <th>الهاتف الرئيسى</th>
                                <th>طريقه الدفع</th>
                                <th>السعر</th>
                                <th>التاريخ</th>
                                <th>الأدوات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in _Context.TblBalanceTransactions.Where(a => a.IsDeleted != true && a.Pending == true).OrderByDescending(a => a.ID).ToList())
                            {
                                string STDName = item.TblStudent.FirstName + ' ' + item.TblStudent.SecondName + ' ' + item.TblStudent.ThirdName;
                                <tr>
                                    <td>@item.ID</td>
                                    <td>@STDName</td>
                                    <td>@item.TblStudent.PhoneNumber</td>
                                    <td>@item.PaymentMethod</td>
                                    <td><span class="label label-success ">@item.Price KD</span></td>
                                    <td>@item.CreatedDate.ToString("yyyy-MM-dd hh:mm tt")</td>
                                    <td>
                                        @*<a href="@Url.Action("ConfirmTransaction", "BalanceTransaction", new { id = item.ID })" class="btn btn-xs btn-success" title="تأكيد الشحن" id="btnConfirmTransaction"><i class="fa fa-money fa-lg"></i></a>*@
                                        @*<a href="#reModalRed" class="btn btn-xs btn-warning" id="btnConfirmTransaction">تأكيد الشحن</a>*@
                                        <a href="javascript:showModal('@item.ID','@item.Price','@STDName')" @*href="showModal('@item.Price','@STDName')"*@ class="btn btn-xs btn-warning" id="btnConfirmTransaction_@item.ID">تأكيد الشحن</a>
                                        @*<button onclick="showModal('@item.Price','@STDName')" class="btn btn-xs btn-warning" title="تأكيد الشحن" id="btnConfirmTransaction"><i class="fa fa-money fa-lg"></i></button>*@
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


@*<div class="remodal label-red white" data-remodal-id="reModalRed">
        <h3 id="HModalTitle">تأكيد شحن كارت</h3>
        <p id="PModalBody">
            سيتم تأكيد شحن مبلغ @Model.Price د.ك الي حساب الطال @Model.
        </p>
        <br>
        <a class="remodal-cancel btn-danger btn" href="#">Cancel</a>
        <a class="remodal-confirm ls-light-green-btn btn" id="submitModalRequest" href="#">OK</a>
    </div>*@