SMUniversity/Controllers/AreaController.cs
using SMUModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SMUniversity.Controllers
{
    public class AreaController : Controller
    {
        admin_SMUniversityEntities _Context = new admin_SMUniversityEntities();

        // GET: Area
        public ActionResult Index()
        {
            if (Session["UserID"] == null || Session["BranchID"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }

        public JsonResult getAreas(int GovernorateID)
        {
            try
            {
                string Result = "";
                List<TblArea> _AreasList = _Context.TblAreas.Where(a => a.GovernorateID == GovernorateID && a.IsDeleted != true).ToList();
                Result += "<option value='0'>المنطقة</option>";
                foreach (var area in _AreasList)
                {
                    Result += "<option value='" + area.ID + "'>" + area.NameAr + "</option>";
                }

                return Json(Result);
            }
            catch (Exception ex)
            {
                return Json("ERROR");
            }
        }

        public ActionResult Create()
        {
            try
            {
                if (Session["UserID"] == null || Session["BranchID"] == null)
                {
                    return RedirectToAction("Login", "Home");
                }
                List<TblGovernorate> GovernorateList = _Context.TblGovernorates.Where(a => a.IsDeleted != true).ToList();
                ViewBag.GovernorateList = GovernorateList;

                return View();
            }
            catch (Exception ex)
            {
                TempData["notice"] = "ERROR while processing!";
                return RedirectToAction("Create");
            }
        }

        [HttpPost]
        public ActionResult Create(AreaData _Data)
        {
            try
            {
                if (!string.IsNullOrEmpty(_Data.NameAr) && !string.IsNullOrEmpty(_Data.NameEn) && _Data.GovernorateID > 0)
                {
                    TblArea AreaObj = new TblArea()
                    {
                        NameAr = _Data.NameAr,
                        NameEn = _Data.NameEn,
                        GovernorateID = _Data.GovernorateID,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now
                    };

                    _Context.TblAreas.Add(AreaObj);
                    _Context.SaveChanges();

                    TempData["notice"] = "تم إضافه المنطقه بنجاح";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["notice"] = "من فضلك ادخل البيانات المطلوبه كاملةً";
                    return RedirectToAction("Create");
                }
            }
            catch (Exception ex)
            {
                TempData["notice"] = "ERROR while processing!";
                return RedirectToAction("Create");
            }
        }

        public ActionResult Edit(int AreaID)
        {
            try
            {
                if (Session["UserID"] == null || Session["BranchID"] == null)
                {
                    return RedirectToAction("Login", "Home");
                }
                if (AreaID > 0)
                {
                    TblArea AreaObj = _Context.TblAreas.Where(a => a.ID == AreaID).SingleOrDefault();
                    List<TblGovernorate> GovernoratesList = _Context.TblGovernorates.Where(a => a.IsDeleted != true).ToList();
                    ViewBag.GovernoratesList = GovernoratesList;

                    return View(AreaObj);
                }
                else
                {
                    TempData["notice"] = "ERROR while processing!";
                    return RedirectToAction("Edit", new { AreaID = AreaID });
                }
            }
            catch (Exception ex)
            {
                TempData["notice"] = "ERROR while processing!";
                return RedirectToAction("Edit", new { AreaID = AreaID });
            }
        }

        [HttpPost]
        public ActionResult Edit(AreaData _Data)
        {
            try
            {
                if (_Data.AreaID > 0 && !string.IsNullOrEmpty(_Data.NameAr) && !string.IsNullOrEmpty(_Data.NameEn) && _Data.GovernorateID > 0)
                {
                    TblArea AreaObj = _Context.TblAreas.Where(a => a.ID == _Data.AreaID).SingleOrDefault();
                    if (AreaObj != null)
                    {
                        AreaObj.NameAr = _Data.NameAr;
                        AreaObj.NameEn = _Data.NameEn;
                        AreaObj.GovernorateID = _Data.GovernorateID;
                        AreaObj.UpdatedDate = DateTime.Now;

                        _Context.SaveChanges();

                        TempData["notice"] = "تم تعديل بيانات المنطقه بنجاح";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["notice"] = "بيانات خاطئه";
                        return RedirectToAction("Edit", new { AreaID = _Data.AreaID });
                    }
                }
                else
                {
                    TempData["notice"] = "من فضلك ادخل البيانات المطلوبه كاملةً";
                    return RedirectToAction("Edit", new { AreaID = _Data.AreaID });
                }

            }
            catch (Exception ex)
            {
                TempData["notice"] = "ERROR while processing!";
                return RedirectToAction("Edit", new { AreaID = _Data.AreaID });
            }
        }

        public JsonResult Delete(int AreaID)
        {
            try
            {
                TblArea _Area = _Context.TblAreas.Where(a => a.ID == AreaID).FirstOrDefault();

                _Context.TblAreas.Remove(_Area);
                _Context.SaveChanges();

                return Json("OK");
            }
            catch (Exception ex)
            {
                TempData["notice"] = "لم يتم حذف المنطقه لإرتباطها ببيانات اخري";
                return Json("OK");
            }
        }
    }
}

SMUniversity/Views/Area/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="main-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!--Top header start-->
                <h3 class="ls-top-header">اضافة منطقه</h3>
                <!--Top header end -->
                <!--Top breadcrumb start -->
                <ol class="breadcrumb">
                    <li><a href="/Home/Index"><i class="fa fa-home"></i></a></li>
                    <li><a href="/Area/Index">الرئيسية</a></li>
                    <li class="active"><a href="/Area/Create">اضافة منطقه</a></li>
                </ol>
                <!--Top breadcrumb start -->
            </div>
        </div>
        <!-- Main Content Element  Start-->

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">اضافة منطقه</h3>
                    </div>
                    <form id="AddNewArea" action="/Area/Create" method="post" class="form-horizontal ls_form" enctype='multipart/form-data'>
                        <div class="panel-body form_view">
                            <div class="row ls_divider">
                                <div class="form-group">
                                    <label class="col-md-2 control-label">اسم المنطقه عربي</label>
                                    <div class="col-md-10">
                                        <input type="text"
                                               class="form-control validate[required] text-input"
                                               id="NameAr" name="NameAr" placeholder="ادخل اسم المنطقه عربي" required>
                                    </div>
                                </div>
                            </div>
                            <div class="row ls_divider">
                                <div class="form-group">
                                    <label class="col-md-2 control-label">اسم المنطقه إنجليزي</label>
                                    <div class="col-md-10">
                                        <input type="text"
                                               class="form-control validate[required] text-input"
                                               id="NameEn" name="NameEn" placeholder="ادخل اسم المنطقه إنجليزي" required>
                                    </div>
                                </div>
                            </div>

                            <div class="row ls_divider">
                                <div class="form-group">
                                    <label class="col-md-2 control-label">المحافظة</label>
                                    <div class="col-md-10">
                                        <select class="form-control input-sm" id="GovernorateID" name="GovernorateID" required>
                                            <option value="0">المحافظة</option>
                                            @foreach (var gover in ViewBag.GovernorateList)
                                            {
                                                <option value="@gover.ID">@gover.NameAr</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group" style=" margin: 20px 30px 40px 50px; ">
                                <button class="submit btn-primary btn" type="submit" name="submit">حفظ</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

SMUniversity/Views/Area/Edit.cshtml
@model SMUModels.TblArea
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="main-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!--Top header start-->
                <h3 class="ls-top-header">تعديل منطقه</h3>
                <!--Top header end -->
                <!--Top breadcrumb start -->
                <ol class="breadcrumb">
                    <li><a href="/Home/Index"><i class="fa fa-home"></i></a></li>
                    <li><a href="/Area/Index">الرئيسية</a></li>
                    <li class="active"><a href="/Area/Edit">تعديل منطقه</a></li>
                </ol>
                <!--Top breadcrumb start -->
            </div>
        </div>
        <!-- Main Content Element  Start-->

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">تعديل منطقه</h3>
                    </div>
                    <form id="EditArea" action="/Area/Edit" method="post" class="form-horizontal ls_form" enctype='multipart/form-data'>
                        <input type="hidden" name="AreaID" value="@Model.ID" />

                        <div class="panel-body form_view">
                            <div class="row ls_divider">
                                <div class="form-group">
                                    <label class="col-md-2 control-label">اسم المنطقه عربي</label>
                                    <div class="col-md-10">
                                        <input type="text"
                                               class="form-control validate[required] text-input"
                                               id="NameAr" name="NameAr" placeholder="ادخل اسم المنطقه عربي" value="@Model.NameAr" required>
                                    </div>
                                </div>
                            </div>
                            <div class="row ls_divider">
                                <div class="form-group">
                                    <label class="col-md-2 control-label">اسم المنطقه إنجليزي</label>
                                    <div class="col-md-10">
                                        <input type="text"
                                               class="form-control validate[required] text-input"
                                               id="NameEn" name="NameEn" placeholder="ادخل اسم المنطقه إنجليزي" value="@Model.NameEn" required>
                                    </div>
                                </div>
                            </div>

                            <div class="row ls_divider">
                                <div class="form-group">
                                    <label class="col-md-2 control-label">المحافظة</label>
                                    <div class="col-md-10">
                                        <select class="form-control input-sm" id="GovernorateID" name="GovernorateID" required>
                                            <option value="0">المحافظة</option>
                                            @foreach (var gover in ViewBag.GovernoratesList)
                                            {
                                                if (gover.ID != Model.GovernorateID)
                                                {
                                                    <option value="@gover.ID">@gover.NameAr</option>
                                                }
                                                else
                                                {
                                                    <option value="@gover.ID" selected>@gover.NameAr</option>
                                                }
                                            }
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group" style=" margin: 20px 30px 40px 50px; ">
                                <button class="submit btn-primary btn" type="submit" name="submit">حفظ</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

SMUniversity/Views/Area/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    SMUModels.admin_SMUniversityEntities _Context = new SMUModels.admin_SMUniversityEntities();
}

<link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="~/Content/DataTables/css/buttons.dataTables.min.css" rel="stylesheet" />

<script src="~/Scripts/DataTables/jquery.dataTables.js"></script>
<script src="https://editor.datatables.net/extensions/Editor/js/dataTables.editor.min.js"></script>
@*<script src="~/Scripts/DataTables/dataTables.buttons.min.js"></script>*@
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
<script src="~/Scripts/DataTables/but@*t*@ons.html5.min.js"></script>

<input type="hidden" id="AreaID" />

<div id="main-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!--Top header start-->
                <h3 class="ls-top-header"></h3>
                <!--Top header end -->
                <!--Top breadcrumb start -->
                <ol class="breadcrumb">
                    <li><a href="/Home/Index"><i class="fa fa-home"></i></a></li>
                    <li class="active"><a href="/Area/Index">المناطق</a></li>
                </ol>
                <!--Top breadcrumb start -->
            </div>
        </div>
        <!-- Main Content Element  Start-->

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"></h3>
                    </div>
                    <table id="myDataTable" class="table table-striped table-bordered table-hover display">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>اسم المنطقه عربي</th>
                                <th>اسم المنطقه انجليزي</th>
                                <th>المحافظه</th>
                                <th>تاريخ الإنشاء</th>
                                <th>الأدوات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in _Context.TblAreas.Where(a => a.IsDeleted != true).OrderByDescending(a => a.ID).ToList())
                            {
                                <tr>
                                    <td>@item.ID</td>
                                    <td>@item.NameAr</td>
                                    <td>@item.NameEn</td>
                                    <td>@item.TblGovernorate.NameAr</td>
                                    <td>@item.CreatedDate.ToString("yyyy-MM-dd hh:mm tt")</td>
                                    <td>
                                        <a href="@Url.Action("Edit", "Area", new { AreaID = item.ID })" class="btn btn-xs btn-warning" title="تعديل المنطقه" id="btnEditArea"><i class="fa fa-pencil-square-o"></i></a>
                                        @*<a href="@Url.Action("Delete", "Area", new { AreaID = item.ID })" class="btn btn-xs btn-danger" title="حذف المنطقه" id="btnDeleteArea"><i class="fa fa-minus"></i></a>*@
                                        <a href="javascript:showModal('@item.ID','@item.NameAr')" class="btn btn-xs btn-danger" id="DeleteArea_@item.ID"><i class="fa fa-trash-o"></i></a>
                                        @*<a href="#reModalRed" class="btn btn-round ls-red-btn">Red</a>*@
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function showModal(ID, Name) {
        debugger
        //$('#submitModalRequest').hide();
        //$('.remodal-cancel').text('Close');

        $('#HModalTitle').text('حذف منطقة ' + Name);
        $('#PModalBody').text('سيتم الحذف فقط اذا كانت المنطقه غير مرتبطه ببيانات خاصه بالطلبه او بالمحافظات');
        $("#DeleteArea_" + ID).attr("href", "#reModalRed");
        $('#AreaID').val(ID);
        clickOnModal(ID);
        return false;
    }

    function clickOnModal(ID) {
        var href = $('#DeleteArea_' + ID).attr('href');
        window.location.href = href; //causes the browser to refresh and load the requested url
        return false;
    }

    $(document).on('confirm', '.remodal', function () {
        debugger
        $.ajax({
            type: "POST",
            url: "/Area/Delete",
            cache: false,
            contentType: "application/json; charset=utf-8",
            data: "{AreaID:'" + $('#AreaID').val() +
                "'}",
            dataType: "json",
            processData: false,
            success: function (response) {
                debugger
                location.reload();
            },
            failure: function (errMsg) {
                alert(errMsg);
            }
        });
    });
</script>

SMUniversity/Views/Area/Sample.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="main-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!--Top header start-->
                <h3 class="ls-top-header">اضافة منطقه</h3>
                <!--Top header end -->
                <!--Top breadcrumb start -->
                <ol class="breadcrumb">
                    <li><a href="/Home/Index"><i class="fa fa-home"></i></a></li>
                    <li><a href="/Area/Index">الرئيسية</a></li>
                    <li class="active"><a href="/Area/Create">اضافة منطقه</a></li>
                </ol>
                <!--Top breadcrumb start -->
            </div>
        </div>
        <!-- Main Content Element  Start-->

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">اضافة منطقه</h3>
                    </div>
                    <form id="AddNewArea" action="/Area/Create" method="post" class="form-horizontal ls_form" enctype='multipart/form-data'>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>