SMUniversity/Controllers/HelpQuestionController.cs
using SMUModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SMUniversity.Controllers
{
    public class HelpQuestionController : Controller
    {
        admin_SMUniversityEntities _Context = new admin_SMUniversityEntities();

        // GET: HelpQuestion
        public ActionResult Index()
        {
            if (Session["UserID"] == null || Session["BranchID"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }

        public ActionResult Create()
        {
            try
            {
                if (Session["UserID"] == null || Session["BranchID"] == null)
                {
                    return RedirectToAction("Login", "Home");
                }
                return View();
            }
            catch (Exception ex)
            {
                TempData["notice"] = "ERROR while processing!";
                return RedirectToAction("Create");
            }
        }

        [HttpPost]
        public ActionResult Create(HelpQuestionData _Data)
        {
            try
            {
                if (!string.IsNullOrEmpty(_Data.QuestionAr) && !string.IsNullOrEmpty(_Data.QuestionEn))
                {
                    TblHelpQuestion HelpQuesObj = new TblHelpQuestion()
                    {
                        QuestionAr = _Data.QuestionAr,
                        QuestionEn = _Data.QuestionEn,
                        IsDeleted = false,
                        CreatedDate = DateTime.Now
                    };

                    _Context.TblHelpQuestions.Add(HelpQuesObj);
                    _Context.SaveChanges();

                    TempData["notice"] = "تم إضافه سؤال المساعده بنجاح";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["notice"] = "من فضلك ادخل البيانات المطلوبه كاملةً";
                    return RedirectToAction("Create");
                }

            }
            catch (Exception ex)
            {
                TempData["notice"] = "ERROR while processing!";
                return RedirectToAction("Create");
            }
        }

        public ActionResult Edit(int HelpQuesID)
        {
            try
            {
                if (Session["UserID"] == null || Session["BranchID"] == null)
                {
                    return RedirectToAction("Login", "Home");
                }
                if (HelpQuesID > 0)
                {
                    TblHelpQuestion HelpQuesObj = _Context.TblHelpQuestions.Where(a => a.ID == HelpQuesID).SingleOrDefault();

                    return View(HelpQuesObj);
                }
                else
                {
                    TempData["notice"] = "ERROR while processing!";
                    return RedirectToAction("Edit", new { HelpQuesID = HelpQuesID });
                }
            }
            catch (Exception ex)
            {
                TempData["notice"] = "ERROR while processing!";
                return RedirectToAction("Edit", new { HelpQuesID = HelpQuesID });
            }
        }

        [HttpPost]
        public ActionResult Edit(HelpQuestionData _Data)
        {
            try
            {
                if (_Data.HelpQuestionID > 0 && !string.IsNullOrEmpty(_Data.QuestionAr) && !string.IsNullOrEmpty(_Data.QuestionEn))
                {
                    TblHelpQuestion HelpQuesObj = _Context.TblHelpQuestions.Where(a => a.ID == _Data.HelpQuestionID).SingleOrDefault();
                    if (HelpQuesObj != null)
                    {
                        HelpQuesObj.QuestionAr = _Data.QuestionAr;
                        HelpQuesObj.QuestionEn = _Data.QuestionEn;
                        HelpQuesObj.UpdatedDate = DateTime.Now;

                        _Context.SaveChanges();

                        TempData["notice"] = "تم تعديل بيانات سؤال المساعده بنجاح";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["notice"] = "بيانات خاطئه";
                        return RedirectToAction("Edit", new { HelpQuestionID = _Data.HelpQuestionID });
                    }
                }
                else
                {
                    TempData["notice"] = "من فضلك ادخل البيانات المطلوبه كاملةً";
                    return RedirectToAction("Edit", new { HelpQuestionID = _Data.HelpQuestionID });
                }

            }
            catch (Exception ex)
            {
                TempData["notice"] = "ERROR while processing!";
                return RedirectToAction("Edit", new { HelpQuestionID = _Data.HelpQuestionID });
            }
        }

        public ActionResult StudentComplaints()
        {
            if (Session["UserID"] == null || Session["BranchID"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }

        public JsonResult Delete(int HelpQuesID)
        {
            try
            {
                if (HelpQuesID > 0)
                {
                    //TempData["notice"] = "غير قادر علي الحذف, المحافظه مرتيطه ببيانات في المناطق والطلاب";
                    //return Json("OK");
                    TblHelpQuestion HelpQuestionObj = _Context.TblHelpQuestions.Where(a => a.ID == HelpQuesID).SingleOrDefault();
                    if (HelpQuestionObj != null)
                    {
                        try
                        {
                            TempData["notice"] = "تم حذف السؤال بنجاح";

                            _Context.TblHelpQuestions.Remove(HelpQuestionObj);
                            _Context.SaveChanges();

                            return Json("OK");
                        }
                        catch (Exception ex)
                        {
                            TempData["notice"] = "غير قادر علي الحذف, السؤال مرتيط ببيانات خاصه بشكاوي الطلبه";
                            return Json("OK");
                        }

                    }
                    else
                    {
                        TempData["notice"] = "HelpQuestion not found!";
                        return Json("ERROR");
                    }
                }
                else
                {
                    TempData["notice"] = "HelpQuestion not found!";
                    return Json("ERROR");
                }
            }
            catch (Exception ex)
            {
                TempData["notice"] = "ERROR while processing!";
                return Json("ERROR");
            }
        }

    }
}

SMUniversity/Views/HelpQuestion/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="main-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!--Top header start-->
                <h3 class="ls-top-header">اضافة سؤال مساعده</h3>
                <!--Top header end -->
                <!--Top breadcrumb start -->
                <ol class="breadcrumb">
                    <li><a href="/Home/Index"><i class="fa fa-home"></i></a></li>
                    <li><a href="/HelpQuestion/Index">الرئيسية</a></li>
                    <li class="active"><a href="/HelpQuestion/Create">اضافة سؤال مساعده</a></li>
                </ol>
                <!--Top breadcrumb start -->
            </div>
        </div>
        <!-- Main Content Element  Start-->

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">اضافة جامعة</h3>
                    </div>
                    <form id="AddNewHelpQuestion" action="/HelpQuestion/Create" method="post" class="form-horizontal ls_form" enctype='multipart/form-data'>
                        <div class="panel-body form_view">
                            <div class="row ls_divider">
                                <div class="form-group">
                                    <label class="col-md-2 control-label">السؤال عربي</label>
                                    <div class="col-md-10">
                                        <input type="text"
                                               class="form-control validate[required] text-input"
                                               id="QuestionAr" name="QuestionAr" placeholder="السؤال عربي" required>
                                    </div>
                                </div>
                            </div>
                            <div class="row ls_divider">
                                <div class="form-group">
                                    <label class="col-md-2 control-label">السؤال إنجليزي</label>
                                    <div class="col-md-10">
                                        <input type="text"
                                               class="form-control validate[required] text-input"
                                               id="QuestionEn" name="QuestionEn" placeholder="السؤال إنجليزي" required>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group" style=" margin: 20px 30px 40px 50px; ">
                                <button class="submit btn-primary btn" type="submit" name="submit">حفظ</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

SMUniversity/Views/HelpQuestion/Edit.cshtml
@model SMUModels.TblHelpQuestion
@{
    /**/

    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="main-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!--Top header start-->
                <h3 class="ls-top-header">تعديل السؤال</h3>
                <!--Top header end -->
                <!--Top breadcrumb start -->
                <ol class="breadcrumb">
                    <li><a href="/Home/Index"><i class="fa fa-home"></i></a></li>
                    <li><a href="/HelpQuestion/Index">الرئيسية</a></li>
                    <li class="active"><a href="/HelpQuestion/Edit">تعديل السؤال</a></li>
                </ol>
                <!--Top breadcrumb start -->
            </div>
        </div>
        <!-- Main Content Element  Start-->

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">تعديل السؤال</h3>
                    </div>
                    <form id="EditHelpQuestion" action="/HelpQuestion/Edit" method="post" class="form-horizontal ls_form" enctype='multipart/form-data'>
                        <input type="hidden" name="HelpQuestionID" value="@Model.ID" />

                        <div class="panel-body form_view">
                            <div class="row ls_divider">
                                <div class="form-group">
                                    <label class="col-md-2 control-label">السؤال عربي</label>
                                    <div class="col-md-10">
                                        <input type="text"
                                               class="form-control validate[required] text-input"
                                               id="QuestionAr" name="QuestionAr" placeholder="ادخل السؤال عربي" value="@Model.QuestionAr" required>
                                    </div>
                                </div>
                            </div>
                            <div class="row ls_divider">
                                <div class="form-group">
                                    <label class="col-md-2 control-label">السؤال إنجليزي</label>
                                    <div class="col-md-10">
                                        <input type="text"
                                               class="form-control validate[required] text-input"
                                               id="QuestionEn" name="QuestionEn" placeholder="ادخل السؤال إنجليزي" value="@Model.QuestionEn" required>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group" style=" margin: 20px 30px 40px 50px; ">
                                <button class="submit btn-primary btn" type="submit" name="submit">حفظ</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

SMUniversity/Views/HelpQuestion/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    SMUModels.admin_SMUniversityEntities _Context = new SMUModels.admin_SMUniversityEntities();
}

<link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="~/Content/DataTables/css/buttons.dataTables.min.css" rel="stylesheet" />

<script src="~/Scripts/DataTables/jquery.dataTables.js"></script>
<script src="https://editor.datatables.net/extensions/Editor/js/dataTables.editor.min.js"></script>
@*<script src="~/Scripts/DataTables/dataTables.buttons.min.js"></script>*@
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>

<input type="hidden" id="HelpQuesID" />

<div id="main-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!--Top header start-->
                <h3 class="ls-top-header"></h3>
                <!--Top header end -->
                <!--Top breadcrumb start -->
                <ol class="breadcrumb">
                    <li><a href="/Home/Index"><i class="fa fa-home"></i></a></li>
                    <li class="active"><a href="/Settings/HelpQuestions">اسئلة المساعده</a></li>
                </ol>
                <!--Top breadcrumb start -->
            </div>
        </div>
        <!-- Main Content Element  Start-->

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"></h3>
                    </div>
                    <table id="myDataTable" class="table table-striped table-bordered table-hover display">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>اسم الجامعه عربي</th>
                                <th>اسم الجامعه انجليزي</th>
                                <th>تاريخ الإنشاء</th>
                                <th>الأدوات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in _Context.TblHelpQuestions.Where(a => a.IsDeleted != true).OrderByDescending(a => a.ID).ToList())
                            {
                                <tr>
                                    <td>@item.ID</td>
                                    <td>@item.QuestionAr</td>
                                    <td>@item.QuestionAr</td>
                                    <td>@item.CreatedDate.ToString("yyyy-MM-dd hh:mm tt")</td>
                                    <td>
                                        <a href="@Url.Action("Edit", "HelpQuestion", new { HelpQuesID = item.ID })" class="btn btn-xs btn-warning" title="تعديل السؤال" id="btnEditHelpQues"><i class="fa fa-pencil-square-o"></i></a>
                                        @*<a href="@Url.Action("Delete", "HelpQuestion", new { HelpQuesID = item.ID })" class="btn btn-xs btn-danger" title="حذف السؤال" id="btnDeleteHelpQues"><i class="fa fa-minus"></i></a>*@
                                        <a href="javascript:showModal('@item..ID')" class="btn btn-xs btn-danger" id="DeleteHelpQues_@item.ID"><i class="fa fa-trash-o"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    function showModal(ID, Name) {
        debugger
        //$('#submitModalRequest').hide();
        //$('.remodal-cancel').text('Close');

        $('#HModalTitle').text('حذف فئة الكارت ' + Name);
        $('#PModalBody').text('سيتم الحذف فقط اذا كان السؤال غير مرتبط ببيانات خاصه بشكاوي الطلبه');
        $("#DeleteHelpQues_" + ID).attr("href", "#reModalRed");
        $('#HelpQuesID').val(ID);
        clickOnModal(ID);
        return false;
    }

    function clickOnModal(ID) {
        var href = $('#DeleteHelpQues_' + ID).attr('href');
        window.location.href = href; //causes the browser to refresh and load the requested url
        return false;
    }

    $(document).on('confirm', '.remodal', function () {
        debugger
        $.ajax({
            type: "POST",
            url: "/HelpQuestion/Delete",
            cache: false,
            contentType: "application/json; charset=utf-8",
            data: "{HelpQuesID:'" + $('#HelpQuesID').val() +
                "'}",
            dataType: "json",
            processData: false,
            success: function (response) {
                debugger
                location.reload();
            },
            failure: function (errMsg) {
                alert(errMsg);
            }
        });
    });
</script>

SMUniversity/Views/HelpQuestion/StudentComplaints.cshtml
@{
    ViewBag.Title = "StudentComplaints";
    Layout = "~/Views/Shared/_Layout.cshtml";
    SMUModels.admin_SMUniversityEntities _Context = new SMUModels.admin_SMUniversityEntities();
}

<link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="~/Content/DataTables/css/buttons.dataTables.min.css" rel="stylesheet" />

<script src="~/Scripts/DataTables/jquery.dataTables.js"></script>
<script src="https://editor.datatables.net/extensions/Editor/js/dataTables.editor.min.js"></script>
@*<script src="~/Scripts/DataTables/dataTables.buttons.min.js"></script>*@
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>


<div id="main-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!--Top header start-->
                <h3 class="ls-top-header"></h3>
                <!--Top header end -->
                <!--Top breadcrumb start -->
                <ol class="breadcrumb">
                    <li><a href="/Home/Index"><i class="fa fa-home"></i></a></li>
                    <li class="active"><a href="/HelpQuestion/StudentComplaints">شكاوي الطلبه</a></li>
                </ol>
                <!--Top breadcrumb start -->
            </div>
        </div>
        <!-- Main Content Element  Start-->

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"></h3>
                    </div>
                    <table id="myDataTable" class="table table-striped table-bordered table-hover display">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>اسم الطالب</th>
                                <th>رقم التليفون</th>
                                <th>نص الشكوي</th>
                                <th>سؤال المساعده عربي</th>
                                <th>سؤال المساعده انجليزي</th>
                                <th>تاريخ الإنشاء</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in _Context.TblStudentComplaints.Where(a => a.IsDeleted != true).OrderByDescending(a => a.ID).ToList())
                            {
                                <tr>
                                    <td>@item.ID</td>
                                    <td>@item.TblStudent.FirstName @item.TblStudent.SecondName @item.TblStudent.ThirdName </td>
                                    <td>@item.TblStudent.PhoneNumber</td>
                                    <td>@item.Complaint</td>
                                    <td>@item.TblHelpQuestion.QuestionAr</td>
                                    <td>@item.TblHelpQuestion.QuestionEn</td>
                                    <td>@item.CreatedDate.ToString("yyyy-MM-dd hh:mm tt")</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>