SMUniversity/Controllers/SessionController.cs
using QRCoder;
using SMUModels;
using SMUModels.Classes;
using SMUModels.Handlers;
using SMUModels.ObjectData;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SMUniversity.Controllers
{
    public class SessionController : Controller
    {
        admin_SMUniversityEntities _Context = new admin_SMUniversityEntities();

        // GET: Session
        public ActionResult Index()
        {
            if (Session["UserID"] == null || Session["BranchID"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }

        public ActionResult SessionsList()
        {
            if (Session["UserID"] == null || Session["BranchID"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }

        public ActionResult CoursesList()
        {
            if (Session["UserID"] == null || Session["BranchID"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }

        public ActionResult Create()
        {
            try
            {
                if (Session["UserID"] == null || Session["BranchID"] == null)
                {
                    return RedirectToAction("Login", "Home");
                }
                DateTime CurrentDate = DateTime.Now.Date;
                List<TblUniversity> _UniversityList = _Context.TblUniversities.Where(a => a.IsDeleted != true).ToList();
                List<TblHall> _HallsList = _Context.TblHalls.Where(a => a.IsDeleted != true).ToList();
                List<HallData> Data = new List<HallData>();
                foreach (var item in _HallsList)
                {
                    HallData data = new HallData();
                    TblSession _SessionObj = _Context.TblSessions.Where(a => a.HallID == item.ID && a.IsDeleted != true && DbFunctions.TruncateTime(a.FromDate) <= CurrentDate && DbFunctions.TruncateTime(a.ToDate) >= CurrentDate).FirstOrDefault();
                    data.HallID = item.ID;
                    data.HallCodeAr = item.HallCodeAr;
                    if (_SessionObj == null)
                    {
                        data.Available = true;
                    }
                    else
                    {
                        data.Available = false;
                    }

                    Data.Add(data);
                }
                ViewBag._UniversityList = _UniversityList;
                ViewBag._HallsList = Data;
                //ViewBag._HallsList = _HallsList;

                return View();
            }
            catch (Exception ex)
            {
                TempData["notice"] = "ERROR while processing!";
                return RedirectToAction("Create");
            }

        }

        [HttpPost]
        public ActionResult Create(SessionObj _Data)
        {
            bool Result = false;
            try
            {
                if (!string.IsNullOrEmpty(_Data.Name) && !string.IsNullOrEmpty(_Data.FromDate) && !string.IsNullOrEmpty(_Data.ToDate) && _Data.Type > 0 && _Data.SubjectID > 0 && _Data.LecturerID > 0 && _Data.HallID > 0)
                //if ((!string.IsNullOrEmpty(_Data.Name) && !string.IsNullOrEmpty(_Data.FromDate) && !string.IsNullOrEmpty(_Data.ToDate) && _Data.Type > 0 && _Data.SubjectID > 0 && _Data.LecturerID > 0 && _Data.HallID > 0 && _Data.GeneralSession == false) || (!string.IsNullOrEmpty(_Data.Name) && !string.IsNullOrEmpty(_Data.FromDate) && !string.IsNullOrEmpty(_Data.ToDate) && _Data.Type > 0 && _Data.HallID > 0 && _Data.GeneralSession == true))
                {
                    if (_Data.Type == 1)//session
                    {
                        if ((_Data.Price1 > 0 && _Data.Price2 > 0 && _Data.Price3 > 0) && (_Data.Price1 > _Data.Price2 && _Data.Price1 > _Data.Price3 && _Data.Price2 > _Data.Price3))
                        {
                            Result = true;
                        }
                        else
                        {
                            Result = false;
                            TempData["notice"] = "من فضلك ادخل اسعار صحيحه بحيث يكون المبلغ الاول اكبر من المبلغ الثاني والثالث والملبغ الثاني اكبر من المبلغ الثالث";
                            return RedirectToAction("Create");
                        }
                    }
                    else
                    {
                        if (_Data.Cost > 0 && _Data.SessionPrice > 0)
                        {
                            Result = true;
                        }
                        else
                        {
                            Result = false;
                            TempData["notice"] = "من فضلك ادخل سعر للكورس والسعر في حالة السيشن الواحده";
                            return RedirectToAction("Create");
                        }
                    }
                        //if(_Data.Price1>_Data.Price2 && _Data.Price1 > _Data.Price3 && _Data.Price2 > _Data.Price3)
                        //{
                        if (Result)
                    {
                        Random generator = new Random();
                        TblSession _SessionObj = new TblSession()
                        {
                            Name = _Data.Name,
                            NameEn = _Data.NameEn,
                            Description = !string.IsNullOrEmpty(_Data.Description) ? _Data.Description : "",
                            DescriptionEn = !string.IsNullOrEmpty(_Data.DescriptionEn) ? _Data.DescriptionEn : _Data.Description,
                            FromDate = DateTime.Parse(_Data.FromDate),
                            ToDate = DateTime.Parse(_Data.ToDate),
                            LecturerAccountMethod = _Data.LecturerAccountMethod,
                            Type = _Data.Type == 1 ? true : false,
                            GeneralSession = _Data.GeneralSession,
                            SubjectID = _Data.SubjectID,
                            LecturerID = _Data.LecturerID,
                            //BranchID = _Data.BranchID,
                            BranchID = 3,
                            LecturesCount = _Data.Type == 1 ? 1 : _Data.CourseFromTime.Length,
                            HallID = _Data.HallID,
                            SessionCode = generator.Next(0, 99999).ToString("D5"),
                            IsDeleted = false,
                            CreatedDate = DateTime.Now
                        };
                        //if (!_Data.GeneralSession)
                        //{
                        //    _SessionObj.SubjectID = _Data.SubjectID;
                        //}
                        if (Request.Files["Picture"] != null)
                        {
                            UploadFileResponse Respo = UploadPhoto(Request.Files["Picture"]);
                            if (Respo.Code == 1)
                            {
                                _SessionObj.Picture = Respo.Message;
                            }
                        }

                        _Context.TblSessions.Add(_SessionObj);
                        _Context.SaveChanges();


                        TblSessionDetail _SessionDetailsObj = new TblSessionDetail()
                        {
                            SessionID = _SessionObj.ID,
                            IsDeleted = false,
                            CreatedDate = DateTime.Now
                        };

                        if (_Data.Type == 1) //session
                        {
                            _SessionDetailsObj.Price1 = _Data.Price1;
                            _SessionDetailsObj.Price2 = _Data.Price2;
                            _SessionDetailsObj.Price3 = _Data.Price3;
                            _SessionDetailsObj.Cost = _Data.Price3;

                        }
                        else //cource
                        {
                            _SessionDetailsObj.Cost = _Data.Cost;
                            _SessionDetailsObj.SessionPrice = _Data.SessionPrice;
                        }

                        _Context.TblSessionDetails.Add(_SessionDetailsObj);
                        _Context.SaveChanges();

                        _SessionDetailsObj.SingleSessionQRCode = SaveQRCode((_SessionDetailsObj.ID.ToString() + "," + _Data.Type), string.Format("{0}_QRCode_", _SessionObj.Name));
                        _SessionDetailsObj.QRCode = SaveQRCode((_SessionDetailsObj.ID.ToString() + "," + _Data.Type), string.Format("{0}_QRCode_", _SessionObj.Name));
                        _Context.SaveChanges();

                        if (_Data.Type == 1)
                        {
                            TblSessionTime _SessionTimesObj = new TblSessionTime()
                            {
                                SessionID = _SessionObj.ID,
                                FromTime = DateTime.Parse(_Data.FromDate),
                                ToTime = DateTime.Parse(_Data.ToDate),
                                LectureAr = "المحاضره الأولي",
                                LectureEn = "1st Lecture",
                                IsDeleted = false,
                                CreatedDate = DateTime.Now
                            };
                            _Context.TblSessionTimes.Add(_SessionTimesObj);
                        }
                        else
                        {
                            for (int i = 0; i < _Data.CourseFromTime.ToArray().Length; i++)
                            {
                                TblSessionTime _SessionTimesObj = new TblSessionTime()
                                {
                                    SessionID = _SessionObj.ID,

SMUniversity/Views/Session/CoursesList.cshtml
@{
    ViewBag.Title = "CoursesList";
    Layout = "~/Views/Shared/_Layout.cshtml";
    SMUModels.admin_SMUniversityEntities _Context = new SMUModels.admin_SMUniversityEntities();
}

<link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="~/Content/DataTables/css/buttons.dataTables.min.css" rel="stylesheet" />

<script src="~/Scripts/DataTables/jquery.dataTables.js"></script>
<script src="https://editor.datatables.net/extensions/Editor/js/dataTables.editor.min.js"></script>
@*<script src="~/Scripts/DataTables/dataTables.buttons.min.js"></script>*@
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
<script src="~/Scripts/DataTables/but@*t*@ons.html5.min.js"></script>

<style>
    /* padding-bottom and top for image */
    .mfp-no-margins img.mfp-img {
        padding: 0;
    }
    /* position of shadow behind the image */
    .mfp-no-margins .mfp-figure:after {
        top: 0;
        bottom: 0;
    }
    /* padding for main container */
    .mfp-no-margins .mfp-container {
        padding: 0;
    }
</style>


<div id="main-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!--Top header start-->
                <h3 class="ls-top-header"></h3>
                <!--Top header end -->
                <!--Top breadcrumb start -->
                <ol class="breadcrumb">
                    <li><a href="/Home/Index"><i class="fa fa-home"></i></a></li>
                    <li class="active"><a href="/Session/Index">المحاضرات</a></li>
                </ol>
                <!--Top breadcrumb start -->
            </div>
        </div>
        <!-- Main Content Element  Start-->

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"></h3>
                    </div>
                    <table id="myDataTable" class="table table-striped table-bordered table-hover display">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>QRCode</th>
                                <th>الصوره</th>
                                <th>كود الدوره</th>
                                <th>اسم الدوره</th>
                                <th>اسم المحاضر</th>
                                <th>سعر الدوره</th>
                                <th>سعر الحصه</th>
                                <th>القاعه</th>
                                <th>من</th>
                                <th>الي</th>
                                <th>تاريخ الإنشاء</th>
                                <th>الأدوات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in _Context.TblSessions.Where(a => a.Type == false && a.IsDeleted != true).OrderByDescending(a => a.ID).ToList())
                            {
                                var SessionDetails = _Context.TblSessionDetails.Where(a => a.SessionID == item.ID).FirstOrDefault();
                                string Picture = "http://smuapitest.smartmindkw.com" + item.Picture;
                                string QRCode = "http://smuapitest.smartmindkw.com" + SessionDetails.QRCode;
                            <tr>
                                <td>@item.ID</td>
                                <td><img src='@QRCode' width='107' height='75'></td>
                                @*<td><a class='image-popup-no-margins' href='@QRCode'><img src='@QRCode' width='107' height='75'></a></td>*@
                                <td><img src='@Picture' width='107' height='75'></td>
                                @*<td><a class='image-popup-no-margins' href='@Picture'><img src='@Picture' width='107' height='75'></a></td>*@
                                <td>@item.SessionCode</td>
                                <td>@item.Name</td>
                                <td>@item.TblLecturer.FirstNameAr @item.TblLecturer.SecondNameAr @item.TblLecturer.ThirdNameAr</td>
                                <td><span class="label label-success">@SessionDetails.Cost KD</span></td>
                                <td><span class="label label-success">@SessionDetails.SessionPrice KD</span></td>
                                <td>@item.TblHall.HallCodeAr</td>
                                <td>@item.FromDate.ToString("yyyy-MM-dd")</td>
                                <td>@item.ToDate.ToString("yyyy-MM-dd")</td>
                                <td>@item.CreatedDate.ToString("yyyy-MM-dd hh:mm tt")</td>
                                <td>
                                    @*<a href="@Url.Action("ViewSessions", "Session", new { SessionID = item.ID })" class="btn btn-xs btn-success" title="عرض المحاضرات" id="btnViewSessions"><i class="fa fa-eye fa-lg"></i></a>*@
                                    <a href="@Url.Action("Edit", "Session", new { SessionID = item.ID })" class="btn btn-xs btn-success" title="تعديل المحاضره" id="btnEditSessions"><i class="fa fa-pencil-square-o"></i></a>
                                    <a href="@Url.Action("ViewSessions", "Session", new { SessionID = item.ID })" class="btn btn-xs btn-success" title="عرض المحاضرات" id="btnViewSessions"><i class="fa fa-eye fa-lg"></i></a>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                    @*<a class="image-popup-vertical-fit" href="http://farm9.staticflickr.com/8241/8589392310_7b6127e243_b.jpg" title="Caption. Can be aligned to any side and contain any HTML.">
                        <img src="http://farm9.staticflickr.com/8241/8589392310_7b6127e243_s.jpg" width="75" height="75">
                    </a>
                    <a class="image-popup-fit-width" href="http://farm9.staticflickr.com/8379/8588290361_ecf8c27021_b.jpg" title="This image fits only horizontally.">
                        <img src="http://farm9.staticflickr.com/8379/8588290361_ecf8c27021_s.jpg" width="75" height="75">
                    </a>
                    <a class="image-popup-no-margins" href="http://farm4.staticflickr.com/3721/9207329484_ba28755ec4_o.jpg">
                        <img src="http://farm4.staticflickr.com/3721/9207329484_ba28755ec4_o.jpg" width="107" height="75">
                    </a>*@
                </div>
            </div>
        </div>
    </div>
</div>

@*<script>
    $(document).ready(function () {

        $('.image-popup-vertical-fit').magnificPopup({
            type: 'image',
            closeOnContentClick: true,
            mainClass: 'mfp-img-mobile',
            image: {
                verticalFit: true
            }

        });

        $('.image-popup-fit-width').magnificPopup({
            type: 'image',
            closeOnContentClick: true,
            image: {
                verticalFit: false
            }
        });

        $('.image-popup-no-margins').magnificPopup({
            type: 'image',
            closeOnContentClick: true,
            closeBtnInside: false,
            fixedContentPos: true,
            mainClass: 'mfp-no-margins mfp-with-zoom', // class to remove default margin from left and right side
            image: {
                verticalFit: true
            },
            zoom: {
                enabled: true,
                duration: 300 // don't foget to change the duration also in CSS
            }
        });

    });
    //imageViewer();
</script>*@

SMUniversity/Views/Session/Index.cshtml
@{
    /**/

    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    SMUModels.admin_SMUniversityEntities _Context = new SMUModels.admin_SMUniversityEntities();
}

<link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="~/Content/DataTables/css/buttons.dataTables.min.css" rel="stylesheet" />

<script src="~/Scripts/DataTables/jquery.dataTables.js"></script>
<script src="https://editor.datatables.net/extensions/Editor/js/dataTables.editor.min.js"></script>
@*<script src="~/Scripts/DataTables/dataTables.buttons.min.js"></script>*@
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
<script src="~/Scripts/DataTables/but@*t*@ons.html5.min.js"></script>

<input type="hidden" id="SessionID" />

<div id="main-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!--Top header start-->
                <h3 class="ls-top-header"></h3>
                <!--Top header end -->
                <!--Top breadcrumb start -->
                <ol class="breadcrumb">
                    <li><a href="/Home/Index"><i class="fa fa-home"></i></a></li>
                    <li class="active"><a href="/Session/Index">المحاضرات</a></li>
                </ol>
                <!--Top breadcrumb start -->
            </div>
        </div>
        <!-- Main Content Element  Start-->

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"></h3>
                    </div>
                    <table id="myDataTable" class="table table-striped table-bordered table-hover display">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>كود المحاضره</th>
                                <th>اسم المحاضره</th>
                                <th>اسم المحاضر</th>
                                <th>السعر الأول</th>
                                <th>السعر الثاني</th>
                                <th>السعر الثالث</th>
                                <th>القاعه</th>
                                <th>من</th>
                                <th>الي</th>
                                <th>النوع</th>
                                <th>تاريخ الإنشاء</th>
                                <th>الأدوات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in _Context.TblSessions.Where(a => a.IsDeleted != true).OrderByDescending(a => a.ID).ToList())
                            {
                                var SessionDetails = _Context.TblSessionDetails.Where(a => a.SessionID == item.ID).FirstOrDefault();
                                <tr>
                                    <td>@item.ID</td>
                                    <td>@item.SessionCode</td>
                                    <td>@item.Name</td>
                                    <td>@item.TblLecturer.FirstNameAr @item.TblLecturer.SecondNameAr @item.TblLecturer.ThirdNameAr</td>
                                    <td><span class="label label-success">@(item.Type ? SessionDetails.Cost : SessionDetails.Price1) KD</span></td>
                                    <td><span class="label label-success">@(item.Type ? 0 : SessionDetails.Price2) KD</span></td>
                                    <td><span class="label label-success">@(item.Type ? 0 : SessionDetails.Price3) KD</span></td>
                                    <td>@item.TblHall.HallCodeAr</td>
                                    <td>@item.FromDate.ToString("yyyy-MM-dd")</td>
                                    <td>@item.ToDate.ToString("yyyy-MM-dd")</td>
                                    @if (item.Type)
                                    {
                                        <td>محاضره</td>
                                    }
                                    else
                                    {
                                        <td>دوره</td>
                                    }
                                    <td>@item.CreatedDate.ToString("yyyy-MM-dd hh:mm tt")</td>
                                    <td>
                                        <a href="@Url.Action("ViewSessions", "Session", new { SessionID = item.ID })" class="btn btn-xs btn-success" title="عرض المحاضرات" id="btnViewSessions"><i class="fa fa-eye fa-lg"></i></a>
                                        <a href="@Url.Action("Edit", "Session", new { SessionID = item.ID })" class="btn btn-xs btn-success" title="تعديل المحاضره" id="btnEditSessions"><i class="fa fa-pencil-square-o"></i></a>
                                        <a href="javascript:showModal('@item.ID','@item..Name')" class="btn btn-xs btn-danger" id="DeleteSession_@item.ID"><i class="fa fa-trash-o"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function showModal(ID, Name) {
        debugger
        //$('#submitModalRequest').hide();
        //$('.remodal-cancel').text('Close');

        $('#HModalTitle').text('حذف محاضرة ' + Name);
        $('#PModalBody').text('سيتم الحذف فقط اذا كانت المحاضره غير مرتبطه ببيانات خاصه بالتقييمات او المحاضرات المفضله او الإشتراكات');
        $("#DeleteSession_" + ID).attr("href", "#reModalRed");
        $('#SessionID').val(ID);
        clickOnModal(ID);
        return false;
    }

    function clickOnModal(ID) {
        var href = $('#DeleteSession_' + ID).attr('href');
        window.location.href = href; //causes the browser to refresh and load the requested url
        return false;
    }

    $(document).on('confirm', '.remodal', function () {
        debugger
        $.ajax({
            type: "POST",
            url: "/Session/Delete",
            cache: false,
            contentType: "application/json; charset=utf-8",
            data: "{SessionID:'" + $('#SessionID').val() +
                "'}",
            dataType: "json",
            processData: false,
            success: function (response) {
                debugger
                location.reload();
            },
            failure: function (errMsg) {
                alert(errMsg);
            }
        });
    });
</script>

SMUniversity/Views/Session/LecturesByPercentageList.cshtml
@{
    ViewBag.Title = "LecturesByPercentageList";
    Layout = "~/Views/Shared/_Layout.cshtml";
    SMUModels.admin_SMUniversityEntities _Context = new SMUModels.admin_SMUniversityEntities();
}

<link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="~/Content/DataTables/css/buttons.dataTables.min.css" rel="stylesheet" />

<script src="~/Scripts/DataTables/jquery.dataTables.js"></script>
<script src="https://editor.datatables.net/extensions/Editor/js/dataTables.editor.min.js"></script>
@*<script src="~/Scripts/DataTables/dataTables.buttons.min.js"></script>*@
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
<script src="~/Scripts/DataTables/but@*t*@ons.html5.min.js"></script>


<div id="main-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <!--Top header start-->
                <h3 class="ls-top-header"></h3>
                <!--Top header end -->
                <!--Top breadcrumb start -->
                <ol class="breadcrumb">
                    <li><a href="/Home/Index"><i class="fa fa-home"></i></a></li>
                    <li class="active"><a href="/Session/Index">المحاضرات</a></li>
                </ol>
                <!--Top breadcrumb start -->
            </div>
        </div>
        <!-- Main Content Element  Start-->

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"></h3>
                    </div>
                    <table id="myDataTable" class="table table-striped table-bordered table-hover display">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>QRCode</th>
                                <th>الصوره</th>
                                <th>كود المحاضره</th>
                                <th>اسم المحاضره</th>
                                <th>اسم المحاضر</th>
                                <th>السعر الأول</th>
                                <th>السعر الثاني</th>
                                <th>السعر الثالث</th>
                                <th>القاعه</th>
                                <th>من</th>
                                <th>الي</th>
                                <th>تاريخ الإنشاء</th>
                                <th>الأدوات</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in _Context.TblSessions.Where(a => a.Type == true && a.LecturerAccountMethod == 2 && a.IsDeleted != true).OrderByDescending(a => a.ID).ToList())
                            {
                                var SessionDetails = _Context.TblSessionDetails.Where(a => a.SessionID == item.ID).FirstOrDefault();
                                string Picture = "http://smuapitest.smartmindkw.com" + item.Picture;
                                string QRCode = "http://smuapitest.smartmindkw.com" + SessionDetails.QRCode;
                                <tr>
                                    <td>@item.ID</td>
                                    <td><img src='@QRCode' width='107' height='75'></td>
                                    @*<td><a class='image-popup-no-margins' href='@QRCode'><img src='@QRCode' width='107' height='75'></a></td>*@
                                    <td><img src='@Picture' width='107' height='75'></td>
                                    @*<td><a class='image-popup-no-margins' href='@Picture'><img src='@Picture' width='107' height='75'></a></td>*@
                                    <td>@item.SessionCode</td>
                                    <td>@item.Name</td>
                                    <td>@item.TblLecturer.FirstNameAr @item.TblLecturer.SecondNameAr @item.TblLecturer.ThirdNameAr</td>
                                    <td><span class="label label-success">@SessionDetails.Price1 KD</span></td>
                                    <td><span class="label label-success">@SessionDetails.Price2 KD</span></td>
                                    <td><span class="label label-success">@SessionDetails.Price3 KD</span></td>
                                    <td>@item.TblHall.HallCodeAr</td>
                                    <td>@item.FromDate.ToString("yyyy-MM-dd")</td>
                                    <td>@item.ToDate.ToString("yyyy-MM-dd")</td>
                                    <td>@item.CreatedDate.ToString("yyyy-MM-dd hh:mm tt")</td>
                                    <td>
                                        <a href="@Url.Action("GetSessionStudents", "Session", new { SessionID = item.ID })" class="btn btn-xs btn-success" title="عرض الطلبه" id="btnViewSessionStudents"><i class="fa fa-eye fa-lg"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>